"""Voice Agent Phone Number can be nullable and new system_prompt column

Revision ID: dd48902efa5b
Revises: bbe3a1901cd4
Create Date: 2025-10-07 05:31:49.970495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd48902efa5b'
down_revision: Union[str, Sequence[str], None] = 'bbe3a1901cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_agents', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.alter_column('voice_agents', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_agents', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('voice_agents', 'system_prompt')
    # ### end Alembic commands ###
